[package]
name = "devsarim/quran-api"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
t = "osyrisrblx/t@3.0.0"